export interface Item {
  w: number
  h: number
  ilvl: number
  icon: string
  league: string
  item_id: string
  name: string
  type_line: string
  identified: boolean
  verified: boolean
  corrupted: boolean
  locked_to_character: boolean
  frame_type: number
  x: number
  y: number
  inventory_id: string
  account_name: string
  stash_id: string
  socket_amount: number
  link_amount: number
  available: boolean
  added_ts: number
  updated_ts: number
  flavour_text: string
  price: string
  enchanted: boolean
  crafted: boolean
}
